### ISSUE TITLE
Problem with the glyph "Boötes" with open Computer

### ISSUE THREAD

**Issue by HDL34** [MrJake222/AUNIS#151] opened 2020-04-24 15:01 UTC
When I make a sequence with open Computer and I have the glyph "Boötes" in 5th position, the sequence blocks on the glyph in question. If I remove the accent on the "o" of the name, the sequence is performed in full but I have a dial fail at the end of the sequence.
![image](https://user-images.githubusercontent.com/61374058/80226917-436c5b80-864d-11ea-9363-58cbf9f9be4b.png)

**Comment by KamaroTheN7** [comment] 2020-04-24 15:07
I have that same, but I think that's normal intended behavior because "o" it's not equal to "ö".

Wysłane z aplikacji Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by NovaXeros** [comment] 2020-04-24 21:06
I'm not sure the failing to open is related to the Bootes chevron.

I have an address in which I use "Bootes" to dial (not with the accent) and it dials perfectly fine on version 1.9.5. Are you sure you've programmed in the correct address/chevron order?

**Comment by KamaroTheN7** [comment] 2020-04-24 21:15
> 
> 
> I'm not sure the failing to open is related to the Bootes chevron.
> 
> I have an address in which I use "Bootes" to dial (not with the accent) and it dials perfectly fine on version 1.9.5. Are you sure you've programmed in the correct address/chevron order?

I'm not, I currently don't have survival world, I now testing AUNIS with other mods, computer programs, it self (and others that are necessary to properly run it). Lets wait to the author of the mod.

**Comment by PoltixeTheDerg** [comment] 2020-04-25 01:52
Can you dial the address using a DHD? If not, then there is a problem with the address, not the Bootes glyph.

**Comment by HDL34** [comment] 2020-04-25 07:05
Yes with the DHD, I have no problem. 
If the glyph "Boötes" and in first position, I have to write it like this: "Bootes" otherwise the sequence does not start. I have not yet tested on another position in the sequence but in 5th position in any case it does not want.
If you want to test the problem, place the door with the address in question at the following coordinate:
178 65 200.

**Comment by PoltixeTheDerg** [comment] 2020-04-25 08:25
Well, `Bootes` and `Boötes` are interchangeable in OC, the reason `Boötes` is not working for you is probably just some encoding error. And using the same address I am not able to replicate your issue.
https://files.catbox.moe/mdf0mt.png

**Comment by PoltixeTheDerg** [comment] 2020-04-25 08:34
Is there any output in the game console about a possible error? AUNIS logs a lot of errors in the console.

**Comment by MrJake222** [comment] 2020-04-25 08:37
The ö is unicode ö. I'm not sure how this behaves on non-unicode setups xD

**Comment by HDL34** [comment] 2020-04-25 15:31
You also don't use the same program to start the sequence.
so tried with this one:
[dial 2.zip](https://github.com/MrJake222/AUNIS/files/4533354/dial.2.zip)

**Comment by MrJake222** [comment] 2020-04-25 16:17
Can you provide me with your file, with the "ö" in it?

**Comment by HDL34** [comment] 2020-04-25 18:08
Here is
[dial 2.zip](https://github.com/MrJake222/AUNIS/files/4533705/dial.2.zip)

**Comment by PoltixeTheDerg** [comment] 2020-04-25 20:29
I was able to replicate the bug where the `Boötes` glyph with the `ö` does not engage, but I was not able to replicate the dialing sequence failing.
Can you try using a different dialing program, such as Augurs, which handles and displays all errors properly? It would make it a lot easier to tell whats going on.

Here is his dialer:
`pastebin get pAqHB264 AuspexGateSystems.lua`

**Comment by HDL34** [comment] 2020-04-26 07:09
Ok thanks. I'm going to try

**Comment by HDL34** [comment] 2020-04-26 07:16
I already had it. But I don't know how it works. I already tested yesterday and the day before yesterday but I never knew how to activate the sequence.

**Comment by MrJake222** [comment] 2020-04-26 08:57
It's not the encoding issue.

> I was able to replicate the bug where the `Boötes` glyph with the `ö` does not engage.

@PoltixeTheDerg How?

**Comment by PoltixeTheDerg** [comment] 2020-04-26 09:40
i just engaged it using `component.stargate.engageSymbol("Boötes")`, didn't work

**Comment by brom10** [comment] 2020-05-13 19:11
I also had a similar problem, when using a computer that dialed addresses that I got from the sgquery command. I would parse the returned string into an address, but when trying to engage the symbol "Boötes" it would not engage, so I had to detect and replace it with "Bootes" for it to work

**Comment by PoltixeTheDerg** [comment] 2020-05-13 20:04
@brom10 what encoding scheme do you use on your computer? I personally use the japanese character set which might be my problem

**Comment by LokeYourLord** [comment] 2020-05-26 09:59
Just faced the same issue, I first thought that the transition from the Milkyway to the Universe Gate doesn't work properly or that the power requirement was too much, but I found that it stops at the 6th Chevron which is where "Boötes" is located. I have a German Keyboard but it does not accept my Ö at all, so what now?

**Comment by MrJake222** [comment] 2021-01-04 15:56
Closing it as no new cases for a long time. Anyone having this issue please comment.

**Closed by MrJake222** 2021-01-04 15:56 UTC
Labels: bug
