### ISSUE TITLE
DHD control crystal

### ISSUE THREAD

**Issue by Moon92** [MrJake222/AUNIS#15] opened 2019-07-13 05:00 UTC
Almost every time I take the DHD control crystal out of the charger it resets back to 0

**Comment by MrJake222** [comment] 2019-07-13 08:43
Steps to reproduce? Any errors in the console?

**Comment by MrJake222** [comment] 2019-07-15 22:40
https://gfycat.com/violetjoyfulbilby

**Comment by MrJake222** [comment] 2020-01-28 19:51
This is some wild bug... I'm trying to fix it maybe the 3rd or the 4th time. Maybe in further Forge versions it will get fixed. It only affects dedicated servers and Creative mode inventory.

https://www.minecraftforge.net/forum/topic/79692-solved-itemstack-capabilities-reset-when-moved-in-creative-inventory/

**Comment by PoltixeTheDerg** [comment] 2020-03-25 20:26
this seems to be fixed, issue needs to be closed

**Comment by MrJake222** [comment] 2020-03-25 22:37
I'm removing Crystal's capability to store power (1.9) whatsoever so yes, I'm closing it.

**Closed by MrJake222** 2020-03-25 22:37 UTC
Labels: bug, on-hold, server
