### ISSUE TITLE
Config options  crash game

### ISSUE THREAD

**Issue by engineeringuofi** [MrJake222/AUNIS#13] opened 2019-07-12 13:35 UTC
I was messing around with the config options and changed the Ring's horizontal range to 750. When I placed a ring controller, I crashed

**Comment by MrJake222** [comment] 2019-07-12 19:29
Rings were never intended for such a great distances... They should be seen as elevators, vertical elevators. Should've included a top limit on that variable but since you've brought it up...

Is it reproducible just by doing the steps you described(changing ring's range and placing controller)?

**Comment by engineeringuofi** [comment] 2019-07-12 19:56
Yes, that's how I did it. When I place the controller, it lags, doesn't show up, and crashes.

**Comment by MrJake222** [comment] 2019-07-12 19:59
I'll investigate that. But no promises, as I said, Rings are not intended for long-distance travel. They were not tested as such...

**Comment by engineeringuofi** [comment] 2019-07-12 20:11
Okay! I just want to get less than 100 blocls

**Comment by MrJake222** [comment] 2019-07-12 20:18
We(me & my brother) played on our survival world with the limit set to 100 i think. So, less than that should be ok.

**Comment by engineeringuofi** [comment] 2019-07-12 20:23
Okay, thank you! I must of put 1000 instead of 100 by accident. I'll check. Thank you!

**Comment by MrJake222** [comment] 2019-07-12 20:28
> changed the Ring's horizontal range to 750

You said 750...

**Comment by engineeringuofi** [comment] 2019-07-12 21:01
Lol. I must've saw 1000 and tried bringing it down to750. Sorry, I meant 100

**Comment by MrJake222** [comment] 2020-01-28 17:57
So, I think I'll close this one by just limiting the possible range. Rings work in a diffrent manner than Stargates. They just scan the area for rings. 1000 blocks radius would require 2000x2000x256 blocks scanned... A lot :) Just use a Stargate already.

**Closed** 2020-01-28 18:06 UTC
Labels: crash
