### ISSUE TITLE
The energy from capacitors does not go out

### ISSUE THREAD

**Issue by MineDragonCZ** [MrJake222/AUNIS#304] opened 2021-04-09 07:04 UTC
Hi!

I´ve got a problem with capacitors.... If i open the gate, the energy from capacitors does not go out...

Here is the print screen of that:
https://cdn.discordapp.com/attachments/597904260633591828/829791700040941618/unknown.png
(The gate was opened to the End)

Here is my aunis_dimensions.json:

```
{
  "planet.Jupiter": {
    "energyToOpen": 14745600,
    "keepAlive": 3200,
    "group": "netherOv"
  },
  "moon.callisto": {
    "energyToOpen": 14745600,
    "keepAlive": 3200,
    "group": "netherOv"
  },
  "moon.moon": {
    "energyToOpen": 7372800,
    "keepAlive": 3200,
    "group": "netherOv"
  },
  "the_end": {
    "energyToOpen": 15529600,
    "keepAlive": 2400,
    "group": "theEnd"
  },
  "moon.titan": {
    "energyToOpen": 14745600,
    "keepAlive": 3200,
    "group": "netherOv"
  },
  "planet.Pluto": {
    "energyToOpen": 25745600,
    "keepAlive": 3200,
    "group": "netherOv"
  },
  "planet.Saturn": {
    "energyToOpen": 3686400,
    "keepAlive": 3200,
    "group": "netherOv"
  },
  "moon.rhea": {
    "energyToOpen": 3686400,
    "keepAlive": 3200,
    "group": "netherOv"
  },
  "planet.mars": {
    "energyToOpen": 11059200,
    "keepAlive": 4800,
    "group": "netherOv"
  },
  "planet.asteroids": {
    "energyToOpen": 14745600,
    "keepAlive": 6400,
    "group": "netherOv"
  },
  "planet.venus": {
    "energyToOpen": 12288000,
    "keepAlive": 5334,
    "group": "netherOv"
  },
  "moon.titania": {
    "energyToOpen": 14745600,
    "keepAlive": 3200,
    "group": "netherOv"
  },
  "planet.Eris": {
    "energyToOpen": 14745600,
    "keepAlive": 3200,
    "group": "netherOv"
  },
  "moon.europa": {
    "energyToOpen": 14745600,
    "keepAlive": 3200,
    "group": "netherOv"
  },
  "moon.iapetus": {
    "energyToOpen": 14745600,
    "keepAlive": 3200,
    "group": "netherOv"
  },
  "overworld": {
    "energyToOpen": 3686400,
    "keepAlive": 3200,
    "group": "netherOv"
  },
  "moon.phobos": {
    "energyToOpen": 14745600,
    "keepAlive": 3200,
    "group": "netherOv"
  },
  "moon.oberon": {
    "energyToOpen": 14745600,
    "keepAlive": 3200,
    "group": "netherOv"
  },
  "planet.Neptune": {
    "energyToOpen": 14745600,
    "keepAlive": 3200,
    "group": "netherOv"
  },
  "moon.ganymede": {
    "energyToOpen": 14745600,
    "keepAlive": 3200,
    "group": "netherOv"
  },
  "planet.kepler22b": {
    "energyToOpen": 20745600,
    "keepAlive": 3200
  },
  "the_nether": {
    "energyToOpen": 14745600,
    "keepAlive": 1600,
    "group": "netherOv"
  },
  "moon.io": {
    "energyToOpen": 14745600,
    "keepAlive": 3200,
    "group": "netherOv"
  },
  "moon.triton": {
    "energyToOpen": 14745600,
    "keepAlive": 3200,
    "group": "netherOv"
  },
  "planet.Mercury": {
    "energyToOpen": 14745600,
    "keepAlive": 3200,
    "group": "netherOv"
  },
  "moon.deimos": {
    "energyToOpen": 14745600,
    "keepAlive": 3200,
    "group": "netherOv"
  },
  "planet.Ceres": {
    "energyToOpen": 14745600,
    "keepAlive": 3200,
    "group": "netherOv"
  },
  "planet.Uranus": {
    "energyToOpen": 14745600,
    "keepAlive": 3200,
    "group": "netherOv"
  }
}
```

Thanks,
MineDragonCZ

**Comment by TheRedCreations** [comment] 2021-04-12 10:26
Duplicate of #303

**Closed** 2023-11-07 16:02 UTC
Labels: duplicate
