### ISSUE TITLE
DHD sound when dialing with a computer

### ISSUE THREAD

**Issue by Nex4rius** [MrJake222/AUNIS#177] opened 2020-05-10 19:00 UTC
I don't think the DHD should make a sound when you are dialing the gate with the computer it should only light up the symbols.

**Comment by KamaroTheN7** [comment] 2020-05-10 19:49
well, this is not MW DHD, but when computer on board wraith dart dial gate, DHD make sound. You can hear gate in background, but its mostly covered by polish lector (this fragment its cuted form my home BluRay collection): https://youtu.be/Hz6r2RYIXz8

**Comment by Nex4rius** [comment] 2020-05-10 22:31
Okay fair enough it's just strange that I'm dialing the gate with my computer and the sound of the DHD is like WAY LOUDER than the stargate itself.

**Comment by ShicKla** [comment] 2020-05-10 23:11
Agreed, the DHD tends to be louder then the gate. May just be proximity to the DHD when dialing. But I do feel like the Gate should have a larger sound radius

**Comment by KamaroTheN7** [comment] 2020-05-10 23:14
Its a know issue, Mr. Jake did not found have to code sound better, cuz it's hard coded in MC.

**Comment by NovaXeros** [comment] 2020-05-12 14:24
I'm currently experimenting with the sounds and think I've figured it out.

Forge has a sound attenuation function built into it's play positioned sound method. The milky way wormhole was set to have a base value of 0.5, presumably as anything higher than this made the audio file sound overpoweringly loud, but that volume level is actually the attenuation volume, not the sound file volume. The sound file volume should be set by the file itself.

My latest commit has "normalised" the wormhole sound to be a little more pleasant on the ears at full volume, and has made the "distance" that the wormhole can be heard opening and closing be configurable.

Tests so far have been good (wormhole open/close can be heard from far away and isn't overly loud when nearby) and reactions from my server players have been positive.

I'll look into the DHD sounds whilst I'm there and see if they can't be normalised a bit, and their attenuation distance reduced as I wouldn't have thought a DHD can be heard from much further than the unit itself, ie. the gate is a huge heavy machine and should be heard from a much larger distance than the DHD which is essentially just a panel of buttons!

**Comment by MrJake222** [comment] 2020-05-12 18:41
The sound is for button press. So technically, dialing from computer it shouldn't be playing. It also annoyed me.

**Comment by NovaXeros** [comment] 2020-05-12 22:20
Whilst I'm working on the SoundHelper aspect, I'll take a look into seeing if I can split out the sound event from the lightup event of the DHD, so that the sound only fires on player interaction. The DHD should still light up as it's a local visual representation of currently locked chevrons, agreed?

**Comment by MrJake222** [comment] 2020-05-13 11:46
Yes, probably you could differentiate based on `stargateState` inside the `activateSymbol` function in `DHDTile`. It should be `DIALING` when using DHD or `DIALING_COMPUTER` when using computer (also `getStargateState().dialingComputer()` should be true).

Keep in mind I'm writing the names from memory and they might be slightly off.

**Comment by wdh7987** [comment] 2020-12-29 05:39
> I don't think the DHD should make a sound when you are dialing the gate with the computer it should only light up the symbols.

If you have a computer hooked up to the stargate, then make sure there is no DHD connected to the same gate. I found this to be the cause of the original issue.

**Closed** 2020-12-29 19:49 UTC
Labels: bug, enhancement
