### ISSUE TITLE
problems with the sound of the AUNIS

### ISSUE THREAD

**Issue by KiraLinux** [MrJake222/AUNIS#186] opened 2020-05-16 22:23 UTC
I can not go to the sounds section in the settings
an attempt to go in there the game crashes

stargate doesn't make sound

aunis-1.12.2-1.9.8-beta
more info in crash logs
[crash-2020-05-17_01.19.29-client.txt](https://github.com/MrJake222/AUNIS/files/4639317/crash-2020-05-17_01.19.29-client.txt)
[latest.log](https://github.com/MrJake222/AUNIS/files/4639318/latest.log)

**Comment by KiraLinux** [comment] 2020-05-16 23:07
tried to run with a minimum of mods
the same thing happens
[crash-2020-05-17_02.04.43-client.txt](https://github.com/MrJake222/AUNIS/files/4639389/crash-2020-05-17_02.04.43-client.txt)
[latest.log](https://github.com/MrJake222/AUNIS/files/4639390/latest.log)

**Comment by KiraLinux** [comment] 2020-05-17 10:32
I clarify the problem, the stargate of the universe does not sound

**Comment by MrJake222** [comment] 2020-05-18 14:24
Could you possibly send me your minimal modpack as a zip or something? I've tried to put one by myself but it's not crashing...

But I've noticed something distracting. Your mods don't have signatures on them(for ex. my copy of thermal expansion has one). Are you sure you're using official sites to download them? Not some 9minecraft shit?

**Comment by KiraLinux** [comment] 2020-05-18 15:39
all mods from the official site

**Comment by KiraLinux** [comment] 2020-05-18 17:24
after deleting options.txt, optionsof.txt it worked

**Comment by KiraLinux** [comment] 2020-05-20 13:38
restarted the game and this problem appeared again

[debug.log](https://github.com/MrJake222/AUNIS/files/4657147/debug.log)
[latest.log](https://github.com/MrJake222/AUNIS/files/4657175/latest.log)
[crash-2020-05-20_16.33.11-client.txt](https://github.com/MrJake222/AUNIS/files/4657177/crash-2020-05-20_16.33.11-client.txt)

**Comment by CryptAlchemy** [comment] 2020-05-25 02:56
Having the same issue over here

**Comment by CryptAlchemy** [comment] 2020-05-25 03:06
Here's some debug info about the crash:

Has to do with sounds or sound options.
Happens when I press on a mod block that emits a **sound**.

Also, can't open the **sound** options or Minecraft crashes.

---- Minecraft Crash Report ----
// Why did you do that?

Time: 2020-05-24 23:04:00 EDT
Description: Updating screen events

java.lang.ArrayIndexOutOfBoundsException

**Comment by KiraLinux** [comment] 2020-05-25 12:56
> Having the same issue over here

I hope the developer has solved this problem

**Comment by MrJake222** [comment] 2020-05-25 13:39
No I haven't. I can't replicate it. Can you send me your `.minecraft` setup with minimal mods where the crash is happening?

**Comment by KiraLinux** [comment] 2020-05-25 15:40
> No I haven't. I can't replicate it. Can you send me your `.minecraft` setup with minimal mods where the crash is happening?

I can’t because the next time you start the game everything began to work with a minimum number of mods
but with a large number the problem persists

**Comment by MrJake222** [comment] 2020-05-26 10:30
So can you determine which one is the problem or which combo is a problem?

**Comment by weberlepecheur** [comment] 2020-05-26 15:43
Hello, same issue here.

I have downloaded CropBlock modpack, and i put Aunis on it, but the sound menu crash, when I remove it, it's works fine.

https://pastebin.com/bW5tU2aS

**Comment by KiraLinux** [comment] 2020-05-26 18:17
> So can you determine which one is the problem or which combo is a problem?

I only have problems with a lot of mods

**Comment by MrJake222** [comment] 2020-05-26 18:27
But probably not with all of them

**Comment by KiraLinux** [comment] 2020-05-26 18:32
before the mod update there was definitely no such problem, I don’t see any sense in playing without sound

try to repeat my assembly or assemblies of two people who also have this problem

**Comment by MrJake222** [comment] 2020-05-26 21:29
Because I've added the sound category in one of the latest updates. It's in your interest to provide me with best possible testing environment. I've tried to download all your mods and according forge's version that were listed in the crash log from 10 days ago, but It just worked perfectly for me :/

**Comment by weberlepecheur** [comment] 2020-05-27 10:39
I tried to make a light modpack with the mod in order to reproduce but i can't unless i hit 140/200 mods. That take a lot of time and i don't understand the conditions to reproduce yet.

Im continue to searching..

**Comment by KiraLinux** [comment] 2020-05-27 12:18
> Because I've added the sound category in one of the latest updates. It's in your interest to provide me with best possible testing environment. I've tried to download all your mods and according forge's version that were listed in the crash log from 10 days ago, but It just worked perfectly for me :/

I deleted the settings file, launched the game, went into the world, there is sound, I adjusted all the sound volumes for myself
I restarted the games, went into the world, run the stargate and there is no sound

vanilla fix immediately showed that there is a problem with the sound and the crash report file also appeared
![2020-05-27_150557](https://user-images.githubusercontent.com/20641834/83017151-d2dda380-a02b-11ea-9d4a-2602b4a688f6.png)
[crash-2020-05-27_15.03.02-client.txt](https://github.com/MrJake222/AUNIS/files/4688623/crash-2020-05-27_15.03.02-client.txt)

here are the logs when the sound worked after deleting the settings file
[debug.log](https://github.com/MrJake222/AUNIS/files/4688587/debug.log)
[latest.log](https://github.com/MrJake222/AUNIS/files/4688591/latest.log)

but the logs when the sound disappeared after restarting the game
[debug.log](https://github.com/MrJake222/AUNIS/files/4688600/debug.log)
[latest.log](https://github.com/MrJake222/AUNIS/files/4688614/latest.log)

I try to help as much as I can

**Comment by BlueVal** [comment] 2020-06-25 00:20
> after deleting options.txt, optionsof.txt it worked

This issue seems to occur with my modpack pretty frequently as well on version 1.9.9

Spent about a good hour testing this and it happened very frequently on the latest 2 versions

On every occasion i tested this particular issue (as it was bugging me today with some crashes) it appears soundCategory_aunis:1.0 was not present in the Options.txt file within the root folder of the minecraft instance on version 1.9.9.

Manually adding this did not have any effect.

It also has this strange visual glitch with Dynamic Surroundings where an empty row appears which may suggest something is wrong there as well?:

![image](https://user-images.githubusercontent.com/36119033/85637938-772f2600-b67c-11ea-9de1-6041e071a777.png)

A work-around seems to be to downgrade to version 1.9.8 and to delete options.txt as mentioned above... this will allow you to change the sound options.

Happens on ATLauncher, Twitch and MultiMC and tested on 2 different systems with different specs with similar result so that appears not to make any difference.

**Comment by BlueVal** [comment] 2020-06-25 00:27
Secondly, it appears after a reload of the game version 1.9.8 will crash as well even if loading fine before.

**Comment by Omega26** [comment] 2020-06-26 13:43
I have the same problem and when I delete the config folder, it works perfectly.

**Comment by AthinCZ** [comment] 2020-07-25 16:23
This bug happens if another mod adds its own sound category, in my case it's IC2. Minecraft probably has a limited number of categories to 10, which also says the exception name "java.lang.ArrayIndexOutOfBoundsException".

@MrJake222 From the modder's point of view, the solution is simple, add to the configuration the option to control whether to use the custom sound category or not. I have no idea if the custom category brings any other changes than just separate volume control, if not then adding this option to the configuration is quite sufficient.

**Comment by SAlexW** [comment] 2020-08-05 15:44
Same problem, but I did a couple of experiments.
First of all: the memory allocated to MC is 10Gb, the number of mods used is 256 including Aunis and VanillaFix to continue the game despite the error. Mod version - 1.12.2-1.9.9.beta.

Experiment 1: Reload audio driver.
With the standard F3+R combination, I rebooted the game audio driver. Because of this, any sound disappears before F3+R is pressed again (this is due to the severity of the modpack itself). But at the same time, the errors associated with the gate sounds disappear, but only with some chance and only for a while (approximately until the opening of the next gate, provided they are constantly opening-closing). Also, I tried to use mods that also reboot the audio drivers, but it didn't bring any results.

Experiment 2: Changing files.
I tried to change both the sound characteristics (quality, frequency and so on) and the file format (waw, mp3). In doing so, I did not make a separate resourcepack, but changed the sounds directly in Aunis.jar because the game first downloads the mod resourses, and then the resourcepack.
Results:
When changing only the characteristics of sound (i.e. the file format of sounds remained the same) - no changes. Error still happens.
When changing format (from ogg to waw or from ogg to mp3) the changed sounds were completely lost, and related errors were also lost.
Conclusion: this problem may be related either to the sound files themselves, or to their in-game renderer, which large modpacks can not cope with. But that's just my guess, based on these experiments. Also, I haven't tried other sound files (for example, from SGCraft mod or try to make them myself).

**Comment by AthinCZ** [comment] 2020-08-08 08:12
I have no idea what this bug is causing, but it has happened since aunis started using its own sound category. So you can add to the configuration whether to use your own sound category or not.

I don't know exactly what my own sound category changes, apart from a separate volume control, if anything, but having functional sounds, although a little different, is worth it to me than not working at all.

By the way, when this bug happens to me, the transport rings are also invisible, but in another modpack where the sounds work, the transport rings are also visible.

**Comment by SAlexW** [comment] 2020-08-08 12:12
> I have no idea what this bug is causing, but it has happened since aunis started using its own sound category. So you can add to the configuration whether to use your own sound category or not.
> 
> I don't know exactly what my own sound category changes, apart from a separate volume control, if anything, but having functional sounds, although a little different, is worth it to me than not working at all.
> 
> By the way, when this bug happens to me, the transport rings are also invisible, but in another modpack where the sounds work, the transport rings are also visible.

About the sound errors. I think it's about Aunis's sound category, too. The thing is that, since I have a big modpack, to eliminate this error, I decided to conduct the last experiment and remove all the sounds from mod. Not with the help of in-game settings, but by pulling sounds out of the mod file. As a result, all the errors disappeared, but it became a bit harder to work with silent gates. 
About the invisible rings. That's another error. If you can reproduce that error again, create an issue.

**Comment by Korvynus** [comment] 2020-09-17 02:36
Yep same issue here with Aunis sound category crashing the game when going in the settings. I rolled back to Aunis 1.9.7 meanwhile you fix the new version.

**Closed** 2020-09-27 12:50 UTC
Labels: crash, hard to reproduce
