### ISSUE TITLE
Bug: Ringtransporter 

### ISSUE THREAD

**Issue by RedstoneSucht** [MrJake222/AUNIS#38] opened 2019-09-13 21:01 UTC

**Comment by RedstoneSucht** [comment] 2019-09-20 20:32
When the Ring_Transporter dials each other at the same time, the blocks around the ring-transporter break it looks like that
![2019-09-20_22 30 42](https://user-images.githubusercontent.com/35812887/65357146-79002080-dbf6-11e9-8614-42850991d540.png)

**Comment by MR-Spagetty** [comment] 2019-11-08 02:33
Why do you have them so close?
Yes they are designed for short range transportation but not that short range

**Comment by RedstoneSucht** [comment] 2019-11-08 11:44
I put them so close, cause of the bug they have to be activated at the same time

**Comment by MrJake222** [comment] 2020-01-31 20:21
I can't reproduce it..., maybe I fixed it along the way :thinking: Anyway, closing this now. If the bug persisit in 1.6, please open a new issue. Thanks.

**Closed by MrJake222** 2020-01-31 20:21 UTC
Labels: bug
