### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Sakhyo** [MrJake222/AUNIS#39] opened 2019-09-28 03:08 UTC
The game crash when trying to enter the stargate active. I paste the error report

--- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
  ForgelinPlugin (Forgelin-1.7.4.jar)
  HCASM (HammerCore-1.12.2-2.0.4.7.jar)
  ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.4.153.jar)
  FCFMLCorePlugin (Finder-Compass-Mod-1.12.2.jar)
  IMLoadingPlugin (infinimend-1.12-1.0.2.jar)
  MuonPlugin (muon-0.2-1.12.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.12.jar)
  JEIDLoadingPlugin (JustEnoughIDs-1.0.2-26.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.6.0-150-universal.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  BIFLoader (BowInfinityFix-1.11.x-1.12.x-rv5.jar)
  FMLModule (mdxlib-3.0.0.6.jar)
  MixinLoaderForge (ValkyrienSkies-1.12.2-1.0.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
Contact their authors BEFORE contacting forge

// Oh - I know what I did wrong!

Time: 9/27/19 11:59 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at mrjake.aunis.packet.gate.renderingUpdate.GateRenderingUpdatePacketToServer.closeGatePacket(GateRenderingUpdatePacketToServer.java:94)
	at mrjake.aunis.tileentity.StargateBaseTile.func_73660_a(StargateBaseTile.java:915)
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at mrjake.aunis.packet.gate.renderingUpdate.GateRenderingUpdatePacketToServer.closeGatePacket(GateRenderingUpdatePacketToServer.java:94)
	at mrjake.aunis.tileentity.StargateBaseTile.func_73660_a(StargateBaseTile.java:915)

-- Block entity being ticked --
Details:
	Name: aunis:stargatebase_block // mrjake.aunis.tileentity.StargateBaseTileOC
	Block type: ID #4466 (tile.aunis.stargatebase_block // mrjake.aunis.block.StargateBaseBlock // aunis:stargatebase_block)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-181,57,633), Chunk: (at 11,3,9 in -12,39; contains blocks -192,0,624 to -177,255,639), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
	Actual block type: ID #4466 (tile.aunis.stargatebase_block // mrjake.aunis.block.StargateBaseBlock // aunis:stargatebase_block)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: Copia de Arkadia
	All players: 1 total; [HookedEntityPlayerMP['Sakhyo'/262, l='Copia de Arkadia', x=-179.70, y=58.00, z=633.67]]
	Chunk stats: ServerChunkCache: 363 Drop: 0
	Level seed: 9209834441347225980
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-224,64,256), Chunk: (at 0,4,0 in -14,16; contains blocks -224,0,256 to -209,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 17137790 game time, 2560986 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 54859 (now: false), thunder time: 150603 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1005896224 bytes (959 MB) / 4523937792 bytes (4314 MB) up to 6429081600 bytes (6131 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_E3 136 mods loaded, 136 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                      | Version                  | Source                                           | Signature                                |
	|:------ |:----------------------- |:------------------------ |:------------------------------------------------ |:---------------------------------------- |
	| LCHIJA | minecraft               | 1.12.2                   | minecraft.jar                                    | None                                     |
	| LCHIJA | mcp                     | 9.42                     | minecraft.jar                                    | None                                     |
	| LCHIJA | FML                     | 8.0.99.99                | forge-1.12.2-14.23.5.2838.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                   | 14.23.5.2838             | forge-1.12.2-14.23.5.2838.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | advancedrocketrycore    | 1                        | minecraft.jar                                    | None                                     |
	| LCHIJA | infinimend              | 1.0.2                    | minecraft.jar                                    | None                                     |
	| LCHIJA | muon                    | 0.2                      | minecraft.jar                                    | None                                     |
	| LCHIJA | bowinfinityfix          | rv5                      | minecraft.jar                                    | e250ba31147feb059b86cfd74ee61a8aeb88fb9b |
	| LCHIJA | obfuscate               | 0.2.6                    | minecraft.jar                                    | None                                     |
	| LCHIJA | opencomputers|core      | 1.7.4.153                | minecraft.jar                                    | None                                     |
	| LCHIJA | uncraftingtable         | 1.8-beta6                | [1.12]UncraftingTable-1.8-beta6(1).jar           | None                                     |
	| LCHIJA | advanced-fishing        | 1.3.2                    | Advanced-Fishing-1.12.2-1.3.2.jar                | None                                     |
	| LCHIJA | advancedcombat          | 1.1.2                    | advancedcombat-1.1.2-[1.12].jar                  | None                                     |
	| LCHIJA | redstoneflux            | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | cofhcore                | 4.6.1                    | CoFHCore-1.12.2-4.6.1.22-universal.jar           | None                                     |
	| LCHIJA | ic2                     | 2.8.109-ex112            | industrialcraft-2-2.8.109-ex112.jar              | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | libvulpes               | 0.4.1.-59                | LibVulpes-1.12.2-0.4.1-59-universal.jar          | None                                     |
	| LCHIJA | advancedrocketry        | 1.6.0.-150               | AdvancedRocketry-1.12.2-1.6.0-150-universal.jar  | None                                     |
	| LCHIJA | anvils                  | 2.0.3                    | AnvilEnchantments-1.12.2-2.0.3.jar               | None                                     |
	| LCHIJA | attributefix            | 1.0.3                    | AttributeFix-1.12.2-1.0.3.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | opencomputers           | 1.7.4.153                | OpenComputers-MC1.12.2-1.7.4.153.jar             | None                                     |
	| LCHIJA | aunis                   | 1.5.0-beta-hotfix3.1     | aunis-1.12.2-1.5.0-beta-hotfix3.1.jar            | None                                     |
	| LCHIJA | autoreglib              | 1.3-15                   | AutoRegLib-1.3-15.jar                            | None                                     |
	| LCHIJA | baublelicious           | 1.4.0-4                  | Baublelicious-Mod-1.12.2.jar                     | None                                     |
	| LCHIJA | baubles                 | 1.5.2                    | Baubles-1.12-1.5.2.jar                           | None                                     |
	| LCHIJA | baubleshud              | 5.0.2                    | BaublesHud-1.12.2-5.0.2.jar                      | None                                     |
	| LCHIJA | bibliotheca             | 1.3.6-1.12.2             | bibliotheca-1.3.6-1.12.2.jar                     | None                                     |
	| LCHIJA | bookshelf               | 2.3.539                  | Bookshelf-1.12.2-2.3.539.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | chameleon               | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                         | None                                     |
	| LCHIJA | chesttransporter        | 2.8.8                    | ChestTransporter-1.12.2-2.8.8.jar                | None                                     |
	| LCHIJA | codechickenlib          | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal(1).jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | cofhworld               | 1.3.0                    | CoFHWorld-1.12.2-1.3.0.6-universal.jar           | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | refinedstorage          | 1.6.13                   | refinedstorage-1.6.13.jar                        | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| LCHIJA | compactmachines3        | 3.0.18                   | compactmachines3-1.12.2-3.0.18-b278.jar          | None                                     |
	| LCHIJA | ctm                     | MC1.12.2-0.3.3.22        | CTM-MC1.12.2-0.3.3.22.jar                        | None                                     |
	| LCHIJA | cucumber                | 1.1.3                    | Cucumber-1.12.2-1.1.3.jar                        | None                                     |
	| LCHIJA | cyclopscore             | 1.3.0                    | CyclopsCore-1.12.2-1.3.0.jar                     | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | disenchanter            | 1.6                      | disenchanter-[1.12]1.6.jar                       | None                                     |
	| LCHIJA | dmcweapons              | 1.0.9                    | DMC_Weapons-1.0.9.jar                            | None                                     |
	| LCHIJA | dldungeonsjbg           | 1.12.10                  | DoomlikeDungeons-1.12.10-MC1.12.2.jar            | None                                     |
	| LCHIJA | thaumcraft              | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar                 | None                                     |
	| LCHIJA | dungeonmobs             | 5.8.4                    | dungeonmobs-5.8.4-MC1.12.2.jar                   | None                                     |
	| LCHIJA | gottschcore             | 1.7.0                    | GottschCore-mc1.12.2-f14.23.5.2768-v1.7.0.jar    | None                                     |
	| LCHIJA | dungeons2               | 1.7.1                    | Dungeons2-mc1.12.2-f14.23.5.2768-v1.7.1.jar      | None                                     |
	| LCHIJA | dungeontactics          | DT-0.15.8                | DungeonTactics-1.12.2-0.15.8.jar                 | None                                     |
	| LCHIJA | ebwizardry              | 4.2.2                    | ElectroblobsWizardry-4.2.2-MC1.12.2.jar          | None                                     |
	| LCHIJA | elevatorid              | 1.3.8                    | ElevatorMod-1.12.2-1.3.8.jar                     | None                                     |
	| LCHIJA | enhancedarmaments       | 1.3.2                    | EnhancedArmaments-1.3.2.jar                      | None                                     |
	| LCHIJA | evilcraft               | 0.10.76                  | EvilCraft-1.12.2-0.10.76.jar                     | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | evilcraftcompat         | 1.0.0                    | EvilCraft-1.12.2-0.10.76.jar                     | None                                     |
	| LCHIJA | zerocore                | 1.12.2-0.1.2.8           | zerocore-1.12.2-0.1.2.8.jar                      | None                                     |
	| LCHIJA | bigreactors             | 1.12.2-0.4.5.67          | ExtremeReactors-1.12.2-0.4.5.67.jar              | None                                     |
	| LCHIJA | findercompass           | 1.12                     | Finder-Compass-Mod-1.12.2.jar                    | None                                     |
	| LCHIJA | sonarcore               | 5.0.19                   | sonarcore-1.12.2-5.0.19-20.jar                   | None                                     |
	| LCHIJA | fluxnetworks            | 4.0.6                    | fluxnetworks-1.12.2-4.0.7-24.jar                 | None                                     |
	| LCHIJA | forgelin                | 1.7.4                    | Forgelin-1.7.4.jar                               | None                                     |
	| LCHIJA | forgivingvoid           | 1.0.23                   | ForgivingVoid_1.12.2-1.0.23.jar                  | None                                     |
	| LCHIJA | fpsreducer              | mc1.12.2-1.12.4          | FpsReducer-mc1.12.2-1.12.4.jar                   | None                                     |
	| LCHIJA | fp                      | 26.4.88                  | Futurepack-1.12.2-26.4.88.jar                    | a8cfb0576c44b2711002b9e45850732f0b8c7cb6 |
	| LCHIJA | fp.api                  | 1.1.0                    | Futurepack-1.12.2-26.4.88.jar                    | None                                     |
	| LCHIJA | gravestone              | 1.2.0                    | GraveStone-1.12.2-Graves-1.2.0.jar               | None                                     |
	| LCHIJA | gravestone-extended     | 1.3.1                    | GraveStone-1.12.2-Extended-1.3.1.jar             | None                                     |
	| LCHIJA | guideapi                | 1.12-2.1.4-57            | Guide-API-1.12-2.1.4-57.jar                      | None                                     |
	| LCHIJA | cgm                     | 0.15.2                   | guns-0.15.2-1.12.2.jar                           | None                                     |
	| LCHIJA | hammertime              | 2.2.0                    | Hammer+Time-2.2.0-1.12.2.jar                     | None                                     |
	| LCHIJA | hammercore              | 2.0.4.7                  | HammerCore-1.12.2-2.0.4.7.jar                    | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LCHIJA | waila                   | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                      | None                                     |
	| LCHIJA | tesla                   | 1.0.63                   | Tesla-1.12.2-1.0.63.jar                          | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | teslacorelib            | 1.0.15                   | tesla-core-lib-1.12.2-1.0.15(2).jar              | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | industrialforegoing     | 1.12.2-1.12.2            | industrialforegoing-1.12.2-1.12.10-234.jar       | None                                     |
	| LCHIJA | mantle                  | 1.12-1.3.3.49            | Mantle-1.12-1.3.3.49.jar                         | None                                     |
	| LCHIJA | mysticalagriculture     | 1.7.3                    | MysticalAgriculture-1.12.2-1.7.3.jar             | None                                     |
	| LCHIJA | jei                     | 4.15.0.280               | jei_1.12.2-4.15.0.280.jar                        | None                                     |
	| LCHIJA | tconstruct              | 1.12.2-2.12.0.135        | TConstruct-1.12.2-2.12.0.135.jar                 | None                                     |
	| LCHIJA | mysticalagradditions    | 1.3.1                    | MysticalAgradditions-1.12.2-1.3.1.jar            | None                                     |
	| LCHIJA | thermalfoundation       | 2.6.2                    | ThermalFoundation-1.12.2-2.6.2.26-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | integrationforegoing    | 1.12.2-1.9               | IntegrationForegoing-1.12.2-1.9.jar              | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
	| LCHIJA | ironchest               | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.67.844.jar                  | None                                     |
	| LCHIJA | journeymap              | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2(1).jar                   | None                                     |
	| LCHIJA | jeid                    | 1.0.2-26                 | JustEnoughIDs-1.0.2-26.jar                       | None                                     |
	| LCHIJA | librarianlib            | 4.12                     | librarianlib-1.12.2-4.12.jar                     | None                                     |
	| LCHIJA | limelib                 | 1.7.12                   | limelib-1.12.2-1.7.12.jar                        | None                                     |
	| LCHIJA | llibrary                | 1.7.9                    | llibrary-1.7.9-1.12.jar                          | None                                     |
	| LCHIJA | lootbags                | 2.5.8.5                  | LootBags-1.12.2-2.5.8.5.jar                      | None                                     |
	| LCHIJA | malisiscore             | 1.12.2-6.5.1-SNAPSHOT    | malisiscore-1.12.2-6.5.1.jar                     | None                                     |
	| LCHIJA | malisisblocks           | 1.12.2-6.1.0             | malisisblocks-1.12.2-6.1.0.jar                   | None                                     |
	| LCHIJA | malisisdoors            | 1.12.2-7.3.0             | malisisdoors-1.12.2-7.3.0.jar                    | None                                     |
	| LCHIJA | malisisswitches         | 1.12.2-5.1.0             | malisisswitches-1.12.2-5.1.0.jar                 | None                                     |
	| LCHIJA | mcjtylib_ng             | 3.0.0                    | mcjtylib-1.12-3.0.0.jar                          | None                                     |
	| LCHIJA | mdxlib                  | 3.0.0.6                  | mdxlib-3.0.0.6.jar                               | None                                     |
	| LCHIJA | patchouli               | 1.0-19                   | Patchouli-1.0-19.jar                             | None                                     |
	| LCHIJA | mmorpg                  | 1.7.7                    | Mine+and+Slash-1.12.2-1.7.7.jar                  | None                                     |
	| LCHIJA | mjrlegendslib           | 1.12.2-1.1.6             | MJRLegendsLib-1.12.2-1.1.6.jar                   | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCHIJA | numina                  | 1.12.2-1.0.38            | Numina-1.12.2-1.0.38.jar                         | None                                     |
	| LCHIJA | powersuits              | 1.12.2-1.0.44            | ModularPowersuits-1.12.2-1.0.44.jar              | None                                     |
	| LCHIJA | morebuckets             | 1.0.4                    | MoreBuckets-1.12.2-1.0.4.jar                     | None                                     |
	| LCHIJA | neat                    | 1.4-16                   | Neat+1.4-16.jar                                  | None                                     |
	| LCHIJA | thermalexpansion        | 5.5.3                    | ThermalExpansion-1.12.2-5.5.3.41-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | omlib                   | 3.1.3-246                | omlib-1.12.2-3.1.3-246.jar                       | None                                     |
	| LCHIJA | openmodularturrets      | 3.1.4-356                | openmodularturrets-1.12.2-3.1.4-356.jar          | None                                     |
	| LCHIJA | plasmacannons           | 0.1                      | PlasmaCannon-1.2.1.jar                           | None                                     |
	| LCHIJA | randomloot              | 1.3                      | RandomLoot-1.4.3.jar                             | None                                     |
	| LCHIJA | raumships               | 1.1.0                    | raumships-1.1.0.jar                              | None                                     |
	| LCHIJA | reborncore              | 3.6.7.210                | RebornCore-1.12.2-3.6.7.210-universal.jar        | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| LCHIJA | rebornstorage           | 1.0.0                    | RebornStorage-1.12.2-3.3.2.79.jar                | None                                     |
	| LCHIJA | reconstructor           | 2.15                     | reconstructor-2.15.jar                           | None                                     |
	| LCHIJA | xreliquary              | 1.12.2-1.3.4.786         | Reliquary-1.12.2-1.3.4.786.jar                   | None                                     |
	| LCHIJA | roguelike               | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar               | None                                     |
	| LCHIJA | subcommonlib            | 1.2.0.1                  | subcommonlib-sublib-1.12.2-1.2.0.4.jar           | None                                     |
	| LCHIJA | rpginventory            | 1.12.2                   | rpginventory-1.12-5.3.0.0.jar                    | None                                     |
	| LCHIJA | ruins                   | 17.2                     | Ruins-1.12.2(1).jar                              | None                                     |
	| LCHIJA | sanlib                  | 1.3.1                    | SanLib-1.12-1.3.1.jar                            | None                                     |
	| LCHIJA | sanplayermodel          | 1.0.3                    | SanLib-1.12-1.3.1.jar                            | None                                     |
	| LCHIJA | t3s4ebw                 | 1.0                      | SeedsForWizardry+1.0+For+MC+Forge+1.12.2.jar     | None                                     |
	| LCHIJA | sgcraft                 | 1.13.2                   | SGCraft-2.0.2.jar                                | None                                     |
	| LCHIJA | silkspawners            | 1.2.5.2                  | silkspawners-1.6(1).jar                          | None                                     |
	| LCHIJA | simplesponge            | 3.6.2                    | SimpleSponge-1.12.2-3.6.2.jar                    | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
	| LCHIJA | theoneprobe             | 1.4.28                   | theoneprobe-1.12-1.4.28.jar                      | None                                     |
	| LCHIJA | thermaldynamics         | 2.5.4                    | ThermalDynamics-1.12.2-2.5.4.18-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | tinkertoolleveling      | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar              | None                                     |
	| LCHIJA | torcherino              | 7.6                      | torcherino-7.6.jar                               | None                                     |
	| LCHIJA | sm                      | 1.3                      | TypicalHeroes-1.0.2.jar                          | None                                     |
	| LCHIJA | universalremote         | 1.12-0.9.10              | UniversalRemote-1.12-0.9.10.jar                  | None                                     |
	| LCHIJA | valkyrienskies          | 1.0                      | ValkyrienSkies-1.12.2-1.0.jar                    | None                                     |
	| LCHIJA | vs_world                | 1.0                      | ValkyrienSkies-1.12.2-1.0.jar                    | None                                     |
	| LCHIJA | vs_control              | 1.0                      | ValkyrienSkies-1.12.2-1.0.jar                    | None                                     |
	| LCHIJA | vs_open_computers       | 1.0                      | ValkyrienSkies-1.12.2-1.0.jar                    | None                                     |
	| LCHIJA | wanionlib               | 1.12.2-1.5               | WanionLib-1.12.2-1.5.jar                         | None                                     |
	| LCHIJA | wit                     | 1.0.25                   | WIT-1.12-1.0.25-44.jar                           | None                                     |
	| LCHIJA | wowweapons              | 0.0.7                    | WoWWeaponsMod-0.0.7.jar                          | None                                     |
	| LCHIJA | orelib                  | 3.5.2.2                  | OreLib-1.12.2-3.5.2.2.jar                        | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | structurize             | 1.12.2-0.10.154-BETA     | structurize-1.12.2-0.10.154-BETA.jar             | None                                     |
	| LCHIJA | librarianliblate        | 4.12                     | librarianlib-1.12.2-4.12.jar                     | None                                     |
	| LCHIJA | minersadvantage         | 1.3.15.191               | MinersAdvantage-1.12.2-1.3.15.192.jar            | None                                     |
	| LCHIJA | teslacorelib_registries | 1.0.15                   | tesla-core-lib-1.12.2-1.0.15(2).jar              | None                                     |
	| LCHIJA | unidict                 | 1.12.2-2.9.3             | UniDict-1.12.2-2.9.3.jar                         | None                                     |

	Loaded coremods (and transformers): 
MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
  
ForgelinPlugin (Forgelin-1.7.4.jar)
  
HCASM (HammerCore-1.12.2-2.0.4.7.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
TransformerLoader (OpenComputers-MC1.12.2-1.7.4.153.jar)
  li.cil.oc.common.asm.ClassTransformer
FCFMLCorePlugin (Finder-Compass-Mod-1.12.2.jar)
  atomicstryker.findercompass.client.coremod.FCTransformer
IMLoadingPlugin (infinimend-1.12-1.0.2.jar)
  net.crazysnailboy.mods.infinimend.asm.IMClassTransformer
MuonPlugin (muon-0.2-1.12.jar)
  gd.izno.mc.muon.MuonClassTransformer
LibrarianLib Plugin (librarianlib-1.12.2-4.12.jar)
  com.teamwizardry.librarianlib.asm.LibLibTransformer
JEIDLoadingPlugin (JustEnoughIDs-1.0.2-26.jar)
  org.dimdev.jeid.JEIDTransformer
AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.6.0-150-universal.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
BIFLoader (BowInfinityFix-1.11.x-1.12.x-rv5.jar)
  com.github.parker8283.bif.Transformer
FMLModule (mdxlib-3.0.0.6.jar)
  com.arisux.mdx.AccessTransformer
MixinLoaderForge (ValkyrienSkies-1.12.2-1.0.jar)
  
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
OreDictionary Info: Registered 1179 names; 1568 stacks.
Pastebin Connection: Okay.
Dependent Mods: None.

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.6.7.210
		Runtime Debofucsation 1
		RenderEngine: 1
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [HookedEntityPlayerMP['Sakhyo'/262, l='Copia de Arkadia', x=-179.70, y=58.00, z=633.67]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 4
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.3.11672 Compatibility Profile Context
	OpenGlRenderer: ATI Radeon 3000 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 6

**Comment by MrJake222** [comment] 2019-09-28 14:36
You sure it's upon entering the Gate. It seems it lacks power and tries to close itself, but It's unable to and looks like the target gate isn't there anymore...

Some steps to reproduce or is it reproducible at all?

**Comment by MrJake222** [comment] 2020-01-31 20:14
Not enough info, closing.

**Closed by MrJake222** 2020-01-31 20:14 UTC
Labels: wontfix
