### ISSUE TITLE
textures disappear when I take my eyes off

### ISSUE THREAD

**Issue by KiraLinux** [MrJake222/AUNIS#127] opened 2020-04-11 20:30 UTC
https://youtu.be/S20u1vFaPnA

**Comment by ShicKla** [comment] 2020-04-11 21:06
Unfortunately that is not caused by AUNIS specifically. It is part of Minecrafts engine when rendering large entities that span past chunk boundaries. Most people are under the impression that a chunks are only in the horizontal. They are also in the vertical too. So they are 16x16x16, not 16x256x16. So if you don't want it to do that move the stargate base block up so it will be in the same chunk as you are.
@MrJake222 I know Immersive Engineering does some kind of trickery to increase the render range of their wires. It my be something to look in to

**Comment by MrJake222** [comment] 2020-04-11 23:20
It's fixed in my dev build so wait patiently :)

**Closed by MrJake222** 2020-04-11 23:20 UTC
