### ISSUE TITLE
Dialing with OC causes a visual bug

### ISSUE THREAD

**Issue by uncoveredkhan09** [MrJake222/AUNIS#58] opened 2020-02-12 12:24 UTC
When dialing with OC the ring can quickly jerk backwards or forwards slightly and it can cause the symbols to not line up or in extreme cases have entirely different symbols at the top 
![IMG_20200211_205248_946](https://user-images.githubusercontent.com/60527794/74334799-9b8f0380-4d68-11ea-9182-6f295fe662b7.jpg)

**Comment by MrJake222** [comment] 2020-02-12 17:46
I'll probably do a full rewrite of the spinning system, because it's a massive hack for it to stop at certain glyph... It was designed to spin the gate on the DHD dial(and stop on user input), but since someone brought up it's non-canon, it's going to be removed and a new system fill follow(with hitting right glyphs as a priority).

**Comment by MrJake222** [comment] 2020-02-21 13:29
Fixed by https://github.com/MrJake222/AUNIS/commit/3f68ddf21ebb1424acdf6ef13af2d61f0f9cc40d

**Closed by MrJake222** 2020-02-21 13:29 UTC
Labels: bug, visuals
